#!/bin/bash

rm -rf ./public
mkdir -p ./public/templates
mkdir -p ./public/js
mkdir -p ./public/js/ext
mkdir -p ./public/css
mkdir -p ./public/img
mkdir -p ./public/audio

# Templates
./node_modules/jaded/bin/jaded -a "jade" -i ./client/templates -o ./public/templates

# Client Config
coffee ./scripts/buildClientConfig.coffee > ./public/js/config.js

# CoffeeScript
coffee -o ./public/js/ -c ./client/js/

# TODO - process that minifies all js
# uglifyjs -nc --unsafe -mt -o ./public/js/main.min.js ./public/js/main.js

# Vein
# readd when contra updates vein to newly built version
# cp ./node_modules/vein/vein.js ./client/js/ext/vein.js

# Pulsar
cp ./node_modules/pulsar/pulsar.js ./client/js/ext/pulsar.js

# Jade
cp ./node_modules/jaded/node_modules/jade/runtime.min.js ./client/js/ext/jade-runtime.js

# Non-built files
cp ./client/*.html ./public
cp -R ./client/js/ext/* ./public/js/ext
cp -R ./client/css/* ./public/css
cp -R ./client/img/* ./public/img
cp -R ./client/audio/* ./public/audio

echo "Build completed!"
