#!/bin/bash
#./build

# create test sandbox
rm -rf ./test/client/public
cp -r ./public ./test/client/public
cp -r ./test/client/jasmine-1.2.0 ./test/client/public/js/ext/jasmine-1.2.0

# overwrite dependencies
coffee -o ./test/client/public/js/ -c ./test/client/stubs/*

# compile spec files
coffee -o ./test/client/public/js/spec/ -c ./test/client/spec/

# run server
open http://localhost:4003
#coffee test/client/SpecServer.coffee
