// Generated by CoffeeScript 1.3.3
(function() {

  describe('page', function() {
    return it('should show the login prompt', function(done) {
      var title;
      title = $('#login-modal h3').val();
      return expect(title).toMatch('Login');
    });
  });

}).call(this);
