#!/usr/local/bin/node

require('coffee-script');
join = require('path').join;
require(join(__dirname, '../app/config'));

// TODO: Exercise for the reader. Add a requireDir function to config which
// will grab all files in a directory and load them into an object
tasks = {
  seed: config.require('scripts/seed'),
  start: config.require('scripts/server'),
  sendRegistration: config.require('scripts/sendRegistration'),
  clearOldChats: config.require('scripts/clearOldChats'),
  printMiddleware: config.require('scripts/printMiddleware'),
  testEmail: config.require('scripts/testEmail'),
  testLogging: config.require('scripts/testLogging')
};

task = process.argv[2]
args = process.argv.slice(3);

if (!task || !tasks[task]) {
  console.log('Available tasks:\n' + Object.keys(tasks).join('\n'));
  process.exit(0);
}
else {
  tasks[task].apply(null, args);
}
