#!/usr/local/bin/node
require('coffee-script');
join = require('path').join;
require(join(__dirname, '../app/config'));

// TODO: Exercise for the reader. Add a requireDir function to config which
// will grab all files in a directory and load them into an object
tasks = {
  seed: 'scripts/seed',
  start: 'scripts/server',
  sendRegistration: 'scripts/sendRegistration',
  clearOldChats: 'scripts/clearOldChats',
  printMiddleware: 'scripts/printMiddleware',
  testEmail: 'scripts/testEmail',
  testLogging: 'scripts/testLogging',
  jasmine: 'scripts/SpecServer'
};

task = process.argv[2]
args = process.argv.slice(3);

if (!task || !tasks[task]) {
  console.log('Available tasks:\n' + Object.keys(tasks).join('\n'));
  process.exit(0);
}
else {
  config.require(tasks[task]).apply(null, args);
}
